quarkus.application.name=c4p-service

quarkus.flow.tracing.enabled=false

quarkus.flow.messaging.defaults-enabled=true

mp.messaging.outgoing.flow-out.connector=smallrye-kafka
mp.messaging.outgoing.flow-out.topic=flow-out
mp.messaging.outgoing.flow-out.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
mp.messaging.outgoing.flow-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer

# https://github.com/quarkiverse/quarkus-flow/issues/193
mp.messaging.incoming.flow-in.connector=smallrye-kafka
mp.messaging.incoming.flow-in.topic=flow-in
mp.messaging.incoming.flow-in.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
mp.messaging.incoming.flow-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

quarkus.flow.messaging.metadata.task-id.key=flowtaskid
quarkus.flow.messaging.metadata.instance-id.key=flowinstanceid

mp.messaging.incoming."proposal.reviewed".connector=smallrye-kafka
mp.messaging.incoming."proposal.reviewed".topic=proposal-reviewed
mp.messaging.incoming."proposal.reviewed".value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
mp.messaging.incoming."proposal.reviewed".key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming."proposal.reviewed".group.id=c4p-service-proposal-reviewed

quarkus.kafka.devservices.shared=true

quarkus.flow.http.client.resilience.circuit-breaker.delay=1s

notification.service.url=http://localhost:8082

quarkus.quinoa.enable-spa-routing=true