%dev.quarkus.http.port=9092

quarkus.flow.tracing.enabled=false
quarkus.flow.messaging.defaults-enabled=true

mp.messaging.outgoing.flow-out.connector=smallrye-kafka
mp.messaging.outgoing.flow-out.topic=flow-out
mp.messaging.outgoing.flow-out.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
mp.messaging.outgoing.flow-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer

# https://github.com/quarkiverse/quarkus-flow/issues/193
mp.messaging.incoming.flow-in.connector=smallrye-kafka
mp.messaging.incoming.flow-in.topic=flow-in
mp.messaging.incoming.flow-in.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
mp.messaging.incoming.flow-in.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer

quarkus.flow.messaging.metadata.task-id.key=flowtaskid
quarkus.flow.messaging.metadata.instance-id.key=flowinstanceid

mp.messaging.outgoing.submission-reviewed.connector=smallrye-kafka
mp.messaging.outgoing.submission-reviewed.topic=submission-reviewed
mp.messaging.outgoing.submission-reviewed.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
mp.messaging.outgoing.submission-reviewed.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.submission-reviewed.cloud-events=true

quarkus.kafka.devservices.shared=true