quarkus.http.port=8081

quarkus.application.name=review-service

mp.messaging.incoming."proposal.submitted".connector=smallrye-kafka
mp.messaging.incoming."proposal.submitted".topic=flow-out
mp.messaging.incoming."proposal.submitted".value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming."proposal.submitted".key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming."proposal.submitted".group.id=review-service

mp.messaging.outgoing."proposal.reviewed".connector=smallrye-kafka
mp.messaging.outgoing."proposal.reviewed".topic=proposal-reviewed
mp.messaging.outgoing."proposal.reviewed".value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
mp.messaging.outgoing."proposal.reviewed".key.serializer=org.apache.kafka.common.serialization.StringSerializer

quarkus.kafka.devservices.shared=true

quarkus.flow.messaging.defaults-enabled=false