quarkus.http.port=9091

mp.messaging.incoming.dev-matheuscruz-proposal-submitted.connector=smallrye-kafka
mp.messaging.incoming.dev-matheuscruz-proposal-submitted.topic=flow-out
mp.messaging.incoming.dev-matheuscruz-proposal-submitted.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.dev-matheuscruz-proposal-submitted.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.dev-matheuscruz-proposal-submitted.group.id=review-service

mp.messaging.outgoing.submission-reviewed.connector=smallrye-kafka
mp.messaging.outgoing.submission-reviewed.topic=submission-reviewed
mp.messaging.outgoing.submission-reviewed.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
mp.messaging.outgoing.submission-reviewed.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.submission-reviewed.cloud-events=true

quarkus.kafka.devservices.shared=true

quarkus.flow.messaging.defaults-enabled=false